name: Build EPF
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install v8unpack
      - run: python build_epf.py ${{ github.workspace }}
      - uses: actions/upload-artifact@v4
        with:
          name: vitrina_export.epf
          path: vitrina_export.epf